# Form implementation generated from reading ui file '.\ui\Diseño_de_Interfaz_Grafica_Reporte.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.WindowModality.NonModal)
        MainWindow.resize(900, 500)
        MainWindow.setMinimumSize(QtCore.QSize(900, 500))
        MainWindow.setMaximumSize(QtCore.QSize(900, 500))
        MainWindow.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.NoContextMenu)
        MainWindow.setStatusTip("")
        MainWindow.setStyleSheet("font-family: \"Poppins\";")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Contenido = QtWidgets.QFrame(parent=self.centralwidget)
        self.Contenido.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.NoContextMenu)
        self.Contenido.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Contenido.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.Contenido.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.Contenido.setObjectName("Contenido")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.Contenido)
        self.verticalLayout.setObjectName("verticalLayout")
        self.fr_encabezado = QtWidgets.QFrame(parent=self.Contenido)
        self.fr_encabezado.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.fr_encabezado.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.fr_encabezado.setObjectName("fr_encabezado")
        self.label = QtWidgets.QLabel(parent=self.fr_encabezado)
        self.label.setGeometry(QtCore.QRect(420, 40, 381, 31))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(22)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_7 = QtWidgets.QLabel(parent=self.fr_encabezado)
        self.label_7.setGeometry(QtCore.QRect(30, 10, 161, 81))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap(".\\ui\\../assets/logo-levapan.png"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.fr_encabezado)
        self.fr_parametros = QtWidgets.QFrame(parent=self.Contenido)
        self.fr_parametros.setStyleSheet("\n"
"background-color: rgb(240, 240, 240);\n"
"")
        self.fr_parametros.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.fr_parametros.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.fr_parametros.setObjectName("fr_parametros")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.fr_parametros)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(parent=self.fr_parametros)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_4 = QtWidgets.QFrame(parent=self.frame)
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_3.setContentsMargins(10, 0, 10, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_9 = QtWidgets.QFrame(parent=self.frame_4)
        self.frame_9.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_4.setContentsMargins(-1, 9, 0, -1)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(parent=self.frame_9)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(10)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.dt_comienzo = QtWidgets.QDateEdit(parent=self.frame_9)
        self.dt_comienzo.setAutoFillBackground(True)
        self.dt_comienzo.setStyleSheet("QDateEdit {\n"
"    background-color: #2b2b2b;\n"
"    color: white;\n"
"    border: 1px solid #444;\n"
"    border-radius: 8px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"\n"
"/* Mes y año */\n"
"QCalendarWidget QToolButton {\n"
"    color: black;\n"
"    background-color: white;\n"
"    font-size: 12px;\n"
"    font-weight: bold;\n"
"    border: none;\n"
"}\n"
"\n"
"\n"
"/* Días */\n"
"QCalendarWidget QSpinBox {\n"
"    color: black;\n"
"    background: white;\n"
"    selection-background-color: #2ecc71;\n"
"    selection-color: white;\n"
"}\n"
"/* Selección */\n"
"QCalendarWidget QAbstractItemView:enabled {\n"
"    color: black;\n"
"    background-color: white;\n"
"    selection-background-color: #2ecc71;\n"
"    selection-color: white;\n"
"}\n"
"")
        self.dt_comienzo.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectionMode.CorrectToPreviousValue)
        self.dt_comienzo.setCalendarPopup(True)
        self.dt_comienzo.setTimeSpec(QtCore.Qt.TimeSpec.LocalTime)
        self.dt_comienzo.setDate(QtCore.QDate(2025, 12, 31))
        self.dt_comienzo.setObjectName("dt_comienzo")
        self.horizontalLayout_4.addWidget(self.dt_comienzo)
        self.verticalLayout_3.addWidget(self.frame_9)
        self.frame_8 = QtWidgets.QFrame(parent=self.frame_4)
        self.frame_8.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_5.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_2 = QtWidgets.QLabel(parent=self.frame_8)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(10)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_5.addWidget(self.label_2)
        self.dt_final = QtWidgets.QDateEdit(parent=self.frame_8)
        self.dt_final.setAutoFillBackground(True)
        self.dt_final.setStyleSheet("QDateEdit {\n"
"    background-color: #2b2b2b;\n"
"    color: white;\n"
"    border: 1px solid #444;\n"
"    border-radius: 8px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"\n"
"/* Mes y año */\n"
"QCalendarWidget QToolButton {\n"
"    color: black;\n"
"    background-color: white;\n"
"    font-size: 12px;\n"
"    font-weight: bold;\n"
"    border: none;\n"
"}\n"
"\n"
"\n"
"/* Días */\n"
"QCalendarWidget QSpinBox {\n"
"    color: black;\n"
"    background: white;\n"
"    selection-background-color: #2ecc71;\n"
"    selection-color: white;\n"
"}\n"
"/* Selección */\n"
"QCalendarWidget QAbstractItemView:enabled {\n"
"    color: black;\n"
"    background-color: white;\n"
"    selection-background-color: #2ecc71;\n"
"    selection-color: white;\n"
"}\n"
"")
        self.dt_final.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectionMode.CorrectToPreviousValue)
        self.dt_final.setCalendarPopup(True)
        self.dt_final.setTimeSpec(QtCore.Qt.TimeSpec.LocalTime)
        self.dt_final.setDate(QtCore.QDate(2025, 12, 31))
        self.dt_final.setObjectName("dt_final")
        self.horizontalLayout_5.addWidget(self.dt_final)
        self.verticalLayout_3.addWidget(self.frame_8)
        self.horizontalLayout_2.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(parent=self.frame)
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_5.setObjectName("frame_5")
        self.label_4 = QtWidgets.QLabel(parent=self.frame_5)
        self.label_4.setGeometry(QtCore.QRect(30, 10, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(12)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.buscar_archivo = QtWidgets.QLineEdit(parent=self.frame_5)
        self.buscar_archivo.setEnabled(False)
        self.buscar_archivo.setGeometry(QtCore.QRect(70, 50, 351, 31))
        self.buscar_archivo.setStyleSheet("QLineEdit{\n"
"border: None;\n"
"background-color:white;\n"
"border-bottom: 2px solid blue;\n"
"}")
        self.buscar_archivo.setObjectName("buscar_archivo")
        self.btn_buscar = QtWidgets.QPushButton(parent=self.frame_5)
        self.btn_buscar.setGeometry(QtCore.QRect(450, 40, 51, 41))
        self.btn_buscar.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    border: none;\n"
"    background-color: transparent;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(255, 255, 255, 255);\n"
"}")
        self.btn_buscar.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\ui\\../assets/carpeta.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_buscar.setIcon(icon)
        self.btn_buscar.setIconSize(QtCore.QSize(24, 24))
        self.btn_buscar.setObjectName("btn_buscar")
        self.horizontalLayout_2.addWidget(self.frame_5)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 2)
        self.verticalLayout_2.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(parent=self.fr_parametros)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_6 = QtWidgets.QFrame(parent=self.frame_2)
        self.frame_6.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_6.setObjectName("frame_6")
        self.label_5 = QtWidgets.QLabel(parent=self.frame_6)
        self.label_5.setGeometry(QtCore.QRect(40, 20, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(12)
        font.setBold(True)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.guardar_archivo = QtWidgets.QLineEdit(parent=self.frame_6)
        self.guardar_archivo.setEnabled(False)
        self.guardar_archivo.setGeometry(QtCore.QRect(90, 60, 351, 31))
        self.guardar_archivo.setStyleSheet("QLineEdit{\n"
"border: None;\n"
"background-color:white;\n"
"border-bottom: 2px solid blue;\n"
"}")
        self.guardar_archivo.setObjectName("guardar_archivo")
        self.btn_guardar = QtWidgets.QPushButton(parent=self.frame_6)
        self.btn_guardar.setGeometry(QtCore.QRect(470, 50, 51, 41))
        self.btn_guardar.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    border: none;\n"
"    background-color: transparent;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(255, 255, 255, 255);\n"
"}")
        self.btn_guardar.setText("")
        self.btn_guardar.setIcon(icon)
        self.btn_guardar.setIconSize(QtCore.QSize(24, 24))
        self.btn_guardar.setObjectName("btn_guardar")
        self.horizontalLayout_3.addWidget(self.frame_6)
        self.frame_7 = QtWidgets.QFrame(parent=self.frame_2)
        self.frame_7.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_7.setObjectName("frame_7")
        self.label_6 = QtWidgets.QLabel(parent=self.frame_7)
        self.label_6.setGeometry(QtCore.QRect(40, 20, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(12)
        font.setBold(True)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.nombre_archivo = QtWidgets.QLineEdit(parent=self.frame_7)
        self.nombre_archivo.setEnabled(True)
        self.nombre_archivo.setGeometry(QtCore.QRect(60, 60, 181, 31))
        self.nombre_archivo.setStyleSheet("QLineEdit{\n"
"border: None;\n"
"background-color:white;\n"
"border-bottom: 2px solid blue;\n"
"}")
        self.nombre_archivo.setObjectName("nombre_archivo")
        self.horizontalLayout_3.addWidget(self.frame_7)
        self.horizontalLayout_3.setStretch(0, 2)
        self.horizontalLayout_3.setStretch(1, 1)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(parent=self.fr_parametros)
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.btn_crear = QtWidgets.QPushButton(parent=self.frame_3)
        self.btn_crear.setGeometry(QtCore.QRect(230, 30, 131, 51))
        self.btn_crear.setStyleSheet("QPushButton {\n"
"    background-color: #2ecc71;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    font-weight: 600;\n"
"}\n"
"\n"
"QPushButtonr:hover {\n"
"    background-color: #28b463;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #239b56;\n"
"}")
        self.btn_crear.setObjectName("btn_crear")
        self.btn_limpiar = QtWidgets.QPushButton(parent=self.frame_3)
        self.btn_limpiar.setGeometry(QtCore.QRect(450, 30, 141, 51))
        self.btn_limpiar.setStyleSheet("QPushButton {\n"
"    background-color: #e67e22;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    font-weight: 600;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ca6f1e;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #af601a;\n"
"}")
        self.btn_limpiar.setObjectName("btn_limpiar")
        self.verticalLayout_2.addWidget(self.frame_3)
        self.verticalLayout.addWidget(self.fr_parametros)
        self.verticalLayout.setStretch(0, 3)
        self.verticalLayout.setStretch(1, 10)
        self.horizontalLayout.addWidget(self.Contenido)
        self.Menu = QtWidgets.QFrame(parent=self.centralwidget)
        self.Menu.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"")
        self.Menu.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.Menu.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.Menu.setObjectName("Menu")
        self.btn_pltReporte = QtWidgets.QPushButton(parent=self.Menu)
        self.btn_pltReporte.setEnabled(True)
        self.btn_pltReporte.setGeometry(QtCore.QRect(0, 0, 58, 54))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Ignored, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_pltReporte.sizePolicy().hasHeightForWidth())
        self.btn_pltReporte.setSizePolicy(sizePolicy)
        self.btn_pltReporte.setStyleSheet("QPushButton {\n"
"    padding: 10px;\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 255, 255, 120);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(255, 255, 255, 120);\n"
"}")
        self.btn_pltReporte.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(".\\ui\\../assets/content_paste1.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_pltReporte.setIcon(icon1)
        self.btn_pltReporte.setIconSize(QtCore.QSize(35, 35))
        self.btn_pltReporte.setObjectName("btn_pltReporte")
        self.btn_pltOperador = QtWidgets.QPushButton(parent=self.Menu)
        self.btn_pltOperador.setEnabled(True)
        self.btn_pltOperador.setGeometry(QtCore.QRect(0, 60, 58, 54))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Ignored, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_pltOperador.sizePolicy().hasHeightForWidth())
        self.btn_pltOperador.setSizePolicy(sizePolicy)
        self.btn_pltOperador.setStyleSheet("QPushButton {\n"
"    padding: 10px;\n"
"    color: white;\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 255, 255, 120);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(255, 255, 255, 120);\n"
"}")
        self.btn_pltOperador.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(".\\ui\\../assets/person_edit1.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_pltOperador.setIcon(icon2)
        self.btn_pltOperador.setIconSize(QtCore.QSize(35, 35))
        self.btn_pltOperador.setObjectName("btn_pltOperador")
        self.horizontalLayout.addWidget(self.Menu)
        self.horizontalLayout.setStretch(0, 15)
        self.horizontalLayout.setStretch(1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 900, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Reporte de Asistencia"))
        self.label.setText(_translate("MainWindow", "REPORTE DE ASISTENCIA"))
        self.label_3.setText(_translate("MainWindow", "Fecha Final:"))
        self.label_2.setText(_translate("MainWindow", "Fecha Inicio:"))
        self.label_4.setText(_translate("MainWindow", "Ubicación Archivo:"))
        self.label_5.setText(_translate("MainWindow", "Guardar Archivo:"))
        self.label_6.setText(_translate("MainWindow", "Nombre:"))
        self.btn_crear.setText(_translate("MainWindow", "CREAR"))
        self.btn_limpiar.setText(_translate("MainWindow", "LIMPIAR"))
